### ISSUE TITLE
Add GitHub with Social links on Blog

### ISSUE THREAD

**Issue by bolotskydev** [neondatabase/website#311]
![Image](https://user-images.githubusercontent.com/13738772/200925073-01054a43-01e2-4c09-9227-897ee07eec6f.png)

Can we add a GitHub button to the social with github.com/neondatabase/neon  as a link?

**Comment by bolotskydev** [comment]
Hey @raoufchebri, can you provide the reasoning behind? 🤔  I'd like to think of better way to resolve the problem, because GitHub link isn't a good fit semantically speaking, as the other buttons serve the common `Share` purpose

**Comment by raoufchebri** [comment]
Hi @bolotskydev . GitHub stars are more valuable than social media follows at the moment. We want to encourage people to star us on GitHub.

**Comment by lnikell** [comment]
Archiving this - feels become irrelevant due to redesign of the blog. We have Github extra link on a left sidebar on index/category pages. For posts where we need extra attention to Github we have a dedicated lazy-block on Wordpress that you can put in any part of the content.



![Image](https://github.com/neondatabase/website/assets/2697570/ade37258-5143-45ac-9435-f23c02736cd4)
