### ISSUE TITLE
update the github banner

### ISSUE THREAD

**Issue by stepashka** [neondatabase/website#605]
We still have a picture with "get early access" CTA in GitHub profile, we need a new banner with a fresh CTA

![Image](https://user-images.githubusercontent.com/445400/226321095-73d9c6e9-00be-4ee5-9397-dd0165661456.jpeg)

**Comment by bolotskydev** [comment]
@stepashka @raoufchebri [here](https://www.figma.com/file/a6W3R8ZzwS8Y6OgD3gTKMA/Covers?node-id=4-3&t=TZxycWHGRPIPVvo2-0) are two options: "classic" and refreshened, please, choose what fits you best

**Comment by raoufchebri** [comment]
@bolotskydev is this the right link? I can't find the banner.

**Comment by danieltprice** [comment]
I believe this link works:
https://www.figma.com/file/a6W3R8ZzwS8Y6OgD3gTKMA/Covers?node-id=85%3A257&t=OKqIEp5G16sNIadn-1

**Comment by jdrumgoole** [comment]
Status?

**Comment by denis-pp** [comment]
@jdrumgoole we designed new banner, here is the [link](https://www.figma.com/file/a6W3R8ZzwS8Y6OgD3gTKMA/Covers?node-id=85%3A257&t=OKqIEp5G16sNIadn-1) also I attached to comment

We don't have an access to update it your repo. Maybe @stepashka could update it? 

![Image](https://user-images.githubusercontent.com/131603105/235702249-a23be4b1-3cc6-4732-b13f-8673771e13da.png)

**Comment by lnikell** [comment]
@jdrumgoole, here is an updated version; please update it on GitHub. In the archive, there are three files. Please use cover-x2-optimized.jpeg since GitHub does not optimize images upon uploading. The other images are for potential future reuse in places where a better quality and resolution is needed.


[github.zip](https://github.com/neondatabase/website/files/11489479/github.zip)
